version: "3"

services:
    notifications-service:
        image: caballero451995/noti-serv:latest
        container_name: notifications-service
        ports:
            - 5001:5001
        restart: always
        depends_on:
            - mongo
        links:
            - mongo
    auth-service:
        image: caballero451995/auth-serv:latest
        container_name: auth-service
        ports:
            - 5000:5000
        restart: always
        depends_on:
            - mongo
        links:
            - mongo
    mongo:
        image: mongo
        restart: always
        volumes:
            - mongodata:/data/db
    nginx:
        build: .
        restart: always
        ports:
            - 80:80
        depends_on:
            - notifications-service
            - auth-service
volumes:
    mongodata:
